-- 코드를 입력하세요
-- 평균 대여 기간이 7일 이상인 자동차 ID와 평균 대여 기간 출력
-- 평균 대여 기간은 소수점 두번째에서 반올림, 평균 대여 기간으로 내림차순, 같으면 ID로 내림차순
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC