-- 코드를 입력하세요
-- FIRST_HALF의 총 주문량, ICECREAM_INFO의 주 성분, 총 주문량 내림차순
SELECT A.FLAVOR
FROM FIRST_HALF A LEFT JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER >= 3000 AND B.INGREDIENT_TYPE LIKE 'fruit%'
ORDER BY TOTAL_ORDER DESC