-- 코드를 작성해주세요
-- 종류별로 가장 큰 물고기의 ID, 이름, 길이 출력
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE=B.FISH_TYPE
WHERE A.LENGTH=(SELECT MAX(LENGTH)
                FROM FISH_INFO
                WHERE FISH_TYPE=A.FISH_TYPE
               )
ORDER BY A.ID

