-- 코드를 작성해주세요
-- 평가 점수(상하반기 합,컬럼명 SCORE)가 가장 높은 사원'들' 점수, 사번, 성명, 직책, 이메일

# SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM HR_EMPLOYEES AS E LEFT JOIN HR_GRADE AS G ON E.EMP_NO=G.EMP_NO
# GROUP BY EMP_NO
# ORDER BY SCORE DESC
# LIMIT 1

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM(
    SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL, RANK() OVER(ORDER BY SUM(G.SCORE) DESC) AS RANKING
    FROM HR_EMPLOYEES AS E JOIN HR_GRADE AS G
    ON E.EMP_NO=G.EMP_NO
    GROUP BY EMP_NO
) AS SUB
WHERE RANKING =1