-- 코드를 작성해주세요
-- DEPT_ID로 연결 가능
-- D에 부서ID, 국문부서명, 영문부서명, 부서 위치
SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS D JOIN HR_EMPLOYEES AS E
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY AVG_SAL DESC